### ISSUE TITLE
replace the current flags to use cobra

### ISSUE THREAD

**Issue by cpanato** [sigstore/gitsign#30]
**Description**
 maybe we can update the existing way to collect flags to use the cobra cli, similar we have for other projects in the org

**Comment by imjasonh** [comment]
It might be possible, but I wonder if it's worth it. The flags to `gitsign` are dictated by Git's expected usage of signing programs, so we wouldn't be able to rename flags for instance. We _might_ be able to add our own flags, if there's some way to configure `git` to call `gitsign` with those flags.

The current `getopt` package is [what `smimesign` uses](https://github.com/github/smimesign/blob/3564e86011859c28b315328027abebb954b6bf6f/main.go#L11), which I assume is why it was used. The docs for for `getopt` say:

> Package getopt (v2) provides traditional getopt processing for implementing commands that use traditional command lines. The standard Go flag package cannot be used to write a program that parses flags the way ls or ssh does, for example.

...though I'm not sure what incompatibilities exactly it's referring to.

I assume Cobra would have the same issues though, since AFAIK it's not intended to be used to match the behavior of ls, ssh, etc. So it might be worth exploring, but I don't think it would necessarily be possible, or even advisable given the compatibility requirements.

**Comment by cpanato** [comment]
i get it, thanks so much for the clarification! <3. will close this for now
